<x-admin-layout title="Repositories">
    @if(session('status'))<div class="mb-5 rounded-2xl border border-sb-accent/25 bg-sb-accent/10 px-4 py-3 text-sm text-sb-accent">{{ session('status') }}</div>@endif
    <section x-data="{ search: '', status: '' }" class="glass-panel overflow-hidden rounded-[26px]">
        <div class="flex flex-wrap items-end justify-between gap-4 p-6"><div><p class="text-[11px] font-semibold uppercase tracking-[0.32em] text-sb-accent">Source management</p><h2 class="mt-2 text-2xl font-semibold text-stone-900 dark:text-stone-100">All repositories</h2></div><div class="flex flex-wrap gap-2"><input x-model="search" placeholder="Search repo or owner…" class="w-56 text-sm"><select x-model="status" class="theme-select text-sm"><option value="">All statuses</option><option value="indexed">Indexed</option><option value="indexing">Indexing</option><option value="error">Error</option></select></div></div>
        <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-y border-white/10 text-xs uppercase tracking-wider text-stone-500"><tr><th class="px-6 py-3">Repo</th><th class="px-6 py-3">Owner</th><th class="px-6 py-3">Status</th><th class="px-6 py-3">Chunks</th><th class="px-6 py-3">Last synced</th><th class="px-6 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-white/10">
            @forelse($sources as $source)@php($meta = $source->meta ?? []) @php($sourceStatus = $meta['status'] ?? ($source->last_synced_at ? 'indexed' : 'indexing'))<tr x-show="(!search || '{{ strtolower($source->identifier.' '.$source->workspace?->user?->email) }}'.includes(search.toLowerCase())) && (!status || status === '{{ $sourceStatus }}')" x-data="{ open: false }"><td class="px-6 py-4 font-medium text-stone-900 dark:text-stone-100">{{ $source->identifier }}@if($sourceStatus === 'error' && !empty($meta['last_error']))<button @click="open = !open" class="ml-2 text-xs text-rose-400 hover:underline">details</button><p x-show="open" x-cloak class="mt-1 max-w-md text-xs text-rose-400">{{ $meta['last_error'] }}</p>@endif</td><td class="px-6 py-4"><p class="text-stone-700 dark:text-stone-300">{{ $source->workspace?->user?->name ?? '—' }}</p><p class="text-xs text-stone-500">{{ $source->workspace?->user?->email ?? '—' }}</p></td><td class="px-6 py-4"><span @class(['rounded-full px-2.5 py-1 text-xs font-semibold','bg-sb-accent/10 text-sb-accent' => $sourceStatus === 'indexed','bg-amber-500/10 text-amber-500' => $sourceStatus === 'indexing','bg-rose-500/10 text-rose-400' => $sourceStatus === 'error','bg-stone-500/10 text-stone-500' => !in_array($sourceStatus, ['indexed','indexing','error'])])>{{ ucfirst(str_replace('_', ' ', $sourceStatus)) }}</span></td><td class="px-6 py-4 font-mono text-stone-500">{{ number_format($source->chunks_count) }}</td><td class="px-6 py-4 text-stone-500">{{ $source->last_synced_at?->format('M j, Y H:i') ?? '—' }}</td><td class="px-6 py-4"><div class="flex justify-end gap-2"><form method="POST" action="{{ route('admin.repos.resync', $source) }}">@csrf<button class="rounded-lg border border-sb-accent/30 px-3 py-1.5 text-xs text-sb-accent">Force re-sync</button></form><form method="POST" action="{{ route('admin.repos.destroy', $source) }}" onsubmit="return confirm('Delete {{ $source->identifier }} and all indexed data for this user?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-500/30 px-3 py-1.5 text-xs text-rose-500">Force delete</button></form></div></td></tr>@empty<tr><td colspan="6" class="px-6 py-10 text-center text-stone-500">No repositories found.</td></tr>@endforelse
        </tbody></table></div>
    </section>
</x-admin-layout>
