<x-admin-layout title="Users">
    <section class="glass-panel overflow-hidden rounded-[26px]">
        <div class="p-6"><p class="text-[11px] font-semibold uppercase tracking-[0.32em] text-sb-accent">Accounts</p><h2 class="mt-2 text-2xl font-semibold text-stone-900 dark:text-stone-100">Users</h2>
            <form method="GET" class="mt-5 grid gap-3 md:grid-cols-4"><input name="search" value="{{ $filters['search'] }}" placeholder="Search name or email" class="md:col-span-2"><select name="status" class="theme-select"><option value="">All statuses</option><option value="active" @selected($filters['status'] === 'active')>Active</option><option value="inactive" @selected($filters['status'] === 'inactive')>Inactive</option></select><select name="plan" class="theme-select"><option value="">All plans</option><option value="free" @selected($filters['plan'] === 'free')>Free</option>@foreach($plans->where('is_free', false) as $plan)<option value="{{ $plan->id }}" @selected($filters['plan'] === $plan->id)>{{ $plan->name }}</option>@endforeach</select><div class="flex gap-2 md:col-span-4"><button class="rounded-xl bg-sb-accent px-4 py-2 text-sm font-semibold text-sb-bg-dark">Apply filters</button><a href="{{ route('admin.users') }}" class="rounded-xl border border-white/10 px-4 py-2 text-sm text-stone-600 dark:text-stone-300">Clear</a></div></form>
        </div>
        <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-y border-white/10 text-xs uppercase tracking-wider text-stone-500"><tr><th class="px-6 py-3">Name</th><th class="px-6 py-3">Email</th><th class="px-6 py-3">Plan</th><th class="px-6 py-3">Joined</th><th class="px-6 py-3">Status</th><th class="px-6 py-3"></th></tr></thead><tbody class="divide-y divide-white/10">
            @if($users->isEmpty())<tr><td colspan="6" class="px-6 py-10 text-center text-sm text-stone-500">No users match your filters.</td></tr>@else @foreach($users as $user)<tr class="transition hover:bg-white/5"><td class="px-6 py-4 font-medium text-stone-900 dark:text-stone-100"><a class="hover:text-sb-accent" href="{{ route('admin.users.show', $user) }}">{{ $user->name }}</a></td><td class="px-6 py-4 text-stone-500 dark:text-stone-400">{{ $user->email }}</td><td class="px-6 py-4"><span class="rounded-full bg-white/5 px-2.5 py-1 text-xs text-stone-500">{{ $user->subscription?->plan?->name ?? 'No plan' }}</span></td><td class="px-6 py-4 text-stone-500 dark:text-stone-400">{{ $user->created_at?->format('M j, Y') }}</td><td class="px-6 py-4"><span @class(['text-xs font-medium', 'text-sb-accent' => $user->active_status, 'text-stone-500' => ! $user->active_status])>{{ $user->active_status ? 'Active' : 'Inactive' }}</span></td><td class="px-6 py-4 text-right"><a href="{{ route('admin.users.show', $user) }}" class="text-xs font-semibold text-sb-accent hover:underline">View</a></td></tr>@endforeach @endif
        </tbody></table></div><div class="border-t border-white/10 px-6 py-4">{{ $users->links() }}</div>
    </section>
</x-admin-layout>
